[default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = ['@uniswap=lib/v3-core/contracts/', '@openzeppelin=lib/openzeppelin-contracts/contracts/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config